### PR TITLE
bump num from 0.2 to 0.4

### PR DESCRIPTION
**Pull request by jqnatividad**
also added missing newline at end of file

### CODE REVIEW

**Comment by dnsl48** [comment]
Hi @jqnatividad, thank you for the contribution!
Before we merge, I would like to understand the problem we are solving here.
Technically, `^0.2` should work gracefully with projects relying on `0.2, 0.3, 0.4`.
If we merge, then we only support projects relying on `0.4`.
Since this library works gracefully with all and we don't specifically rely on any new functionality added in `0.3` and `0.4`, I reckon we might be alright by supporting `>= 0.2`.
Thoughts?

**Comment by jqnatividad** [comment]
Hi @dnsl48 ,
Sorry I missed your query about the PR.
I was just trying to reduce multiple versions on my dependency tree, and fraction was the only one using num 0.2.
Anyway, as per your suggestion changing the num dependency from `^0.2` to `>=0.4` would be great, as it does what I'm trying to do, while not disturbing folks that may need older versions of `num`.

**Comment by jqnatividad** [comment]
And I just created a new PR implementing your suggestion...  thanks again @dnsl48!

**Comment by dnsl48** [comment]
No worries, thank you for the contribution! It's merged :)

**Pull request closed without merging**
