### PR TITLE
52 from str

### PR DESCRIPTION
**Pull request by scott-wilson**
Added support for converting fractions in the form of `num/den` into the `GenericFraction` type. Also, I deprecated the `GenericDecimal::from_decimal_str` and `GenericFraction::from_decimal_str`, since it is replaced with the `FromStr::from_str`.

Lastly, I added some benchmarks. Here's what I get on my machine:

Machine specs:

- Kubuntu 21.10
- AMD Ryzen 9 3950X
- 32 GB GPU

```
Decimal u128/u16 init   time:   [189.36 ns 189.54 ns 189.74 ns]                                  
Found 3 outliers among 100 measurements (3.00%)
  1 (1.00%) low mild
  2 (2.00%) high mild

Decimal i64/u16 init    time:   [286.18 ns 286.29 ns 286.40 ns]                                 
Found 4 outliers among 100 measurements (4.00%)
  2 (2.00%) high mild
  2 (2.00%) high severe

Convert int like from str                                                                             
                        time:   [22.646 ns 22.668 ns 22.690 ns]
Found 6 outliers among 100 measurements (6.00%)
  3 (3.00%) low mild
  3 (3.00%) high mild

Convert float like from str                                                                             
                        time:   [28.013 ns 28.066 ns 28.140 ns]
Found 6 outliers among 100 measurements (6.00%)
  3 (3.00%) low mild
  2 (2.00%) high mild
  1 (1.00%) high severe

Convert fraction like from str                                                                             
                        time:   [30.455 ns 30.643 ns 30.866 ns]

```

### CODE REVIEW

**Comment by scott-wilson** [comment]
Hmm. Apparently I have a bit of cleanup to do. I'll get that sorted soon.

**Comment by scott-wilson** [comment]
Hmm. Apparently I have a bit of cleanup to do. I'll get that sorted soon.

**Comment by scott-wilson** [comment]
Alright, tests should pass now.

Although, the following lint check fails when I run it locally:

```
cargo clippy --all-features -- -D warnings 
    Checking fraction v0.9.0 (/home/scott/Projects/fraction)
error: redundant closure
    --> src/fraction/mod.rs:1827:49
     |
1827 |         iter.fold(GenericFraction::<T>::zero(), |ref s, x| Add::add(s, x))
     |                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace the closure with the function itself: `Add::add`
     |
     = note: `-D clippy::redundant-closure` implied by `-D warnings`
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure

error: redundant closure
    --> src/fraction/mod.rs:1839:48
     |
1839 |         iter.fold(GenericFraction::<T>::one(), |ref s, x| Mul::mul(s, x))
     |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace the closure with the function itself: `Mul::mul`
     |
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure

error: `format!` in `write!` args
   --> src/decimal/mod.rs:112:17
    |
112 | /                 write!(
113 | |                     f,
114 | |                     "GenericDecimal({} | prec={}; {:?}; {})",
115 | |                     format!("{:.1$}", fraction, prec),
...   |
118 | |                     format!("{:.1$}", fraction, debug_prec)
119 | |                 )
    | |_________________^
    |
    = note: `-D clippy::format-in-format-args` implied by `-D warnings`
    = help: combine the `format!(..)` arguments with the outer `write!(..)` call
    = help: or consider changing `format!` to `format_args!`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#format_in_format_args

error: could not compile `fraction` due to 3 previous errors

```

These weren't introduced in my change, so if you're okay with letting this linter fail, then that works for me. Otherwise, I can take a look.

**Comment by dnsl48** [comment]
Yes, those linting issues appear to be false-positives caused by recent clippy updates. The closure might be required to handle the reference correctly. Perhaps write+format might be refactored, but that's not introduced in this PR and I'd rather keep PRs smaller and focus on a single concern, anyway.

Thank you for your beautiful contribution!

**Pull request merged**
